[package]
name = "rustdoc-seeker"
version = "0.1.0"
authors = ["Daniel <daniel65536@gmail.com>"]

[dependencies]
fst = "0.3"
fst-regex = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
string_cache = "0.7"
